### PR TITLE
Build system refactor

### PR DESCRIPTION
**Pull request by ckp95**
- moves to src layout for reasons detailed [here](https://py-pkgs.org/04-package-structure.html#the-source-layout)
- uses poetry for build system and dependency management. this should be transparent to end-users; they don't need poetry to install it, it's only required for developers. I do this because
  - the dependency resolver is (still) better than pip's (notably, the lockfile pins valid dependencies for all platforms, not just the one you're using right now)
  - upgrading packages is better behaved than pip. the venv will always be in a consistent state.
  - it clearly distinguishes between the packages you want to install and the packages that get installed transitively
  - distinction between runtime dependencies and dev dependencies is a first-class citizen
- moved miscellaneous dev tool settings into pyproject.toml to avoid cluttering the repository root directory
- have the version string in pyproject.toml be the single source of truth; runtime code queries it via importlib. this makes bumpversion redundant.

### CODE REVIEW

**Comment by lervag** [comment]
> * moves to src layout for reasons detailed [here](https://py-pkgs.org/04-package-structure.html#the-source-layout)

Great!

> * uses poetry for build system and dependency management.

Also great! I've used it for other projects and I find it very neat. I just never took the time to convert here. Very glad to see it contributed!

> * moved miscellaneous dev tool settings into pyproject.toml to avoid cluttering the repository root directory

Also very good!

> * have the version string in pyproject.toml be the single source of truth; runtime code queries it via importlib. this makes bumpversion redundant.

I'm curious, are you aware of `bumpversion` as a tool? I've used it to simplify the process of bumping the versions. E.g., I run `bump2version patch` and it will both update version strings, make a bump version commit and add a tag. But to work, it requires the config file.

Is there something similar provided with Poetry, perhaps?

> The overall plan I have is that `apy` would eventually depend only on the [`anki` package](https://pypi.org/project/anki/) on PYPI, in its own isolated venv, rather than depending on the one that gets installed by the system package manager. There's just too much that can go wrong with the latter.

I will be more than happy to make this happen!

**Comment by lervag** [comment]
So, as for a review: All thumbs up, except I want to check if there is really no need for bump2version.

**Comment by ckp95** [comment]
>I'm curious, are you aware of bumpversion as a tool? I've used it to simplify the process of bumping the versions. E.g., I run bump2version patch and it will both update version strings, make a bump version commit and add a tag. But to work, it requires the config file.

>Is there something similar provided with Poetry, perhaps?

I didn't know it did the bump version commit and tag as well; I'll put it back.

**Comment by lervag** [comment]
Finally, as a very minor thing that you don't need to consider now: I prefer [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). I'll not enforce it, but in case you are interested, feel free to look into it for potential future PRs :)

**Comment by ckp95** [comment]
Okay I'll keep it in mind about the commits. Also I just checked some more, there is a Poetry plugin that does the bumpversion thing https://github.com/monim67/poetry-bumpversion and you can apparently set it to run in a github workflow based on a tag (so I think the reverse of the bumpversion workflow?)

I don't have any opinion either way (I've always just done this sort of thing manually). I'll keep the bumpversion file the way it is now and we can bikeshed this another time.

**Comment by ckp95** [comment]
Ready for merge I think, can you just double check the bump2version config file behaves as you expect. I did it on a local throwaway branch and it seemed to do the right thing. I also added it to the dev dependencies.

**Comment by lervag** [comment]
Thanks! Great work! I'm merging now. :)

**Pull request merged**
